.. Global includes

.. |DialogueSection| replace:: :class:`~fife_rpg.dialogue.DialogueSection`
.. |Dialogue| replace:: :class:`~fife_rpg.dialogue.Dialogue`
.. |DialogueController| replace:: :class:`~fife_rpg.dialogue.DialogueController`
.. |View| replace:: :class:`View <fife_rpg.mvc.ViewBase>`
.. |RPGWorld| replace:: :class:`~fife_rpg.world.RPGWorld`
.. |Application| replace:: :class:`~fife_rpg.rpg_application.RPGApplication`
.. |Action| replace:: :class:`Action <fife_rpg.actions.base.Base>`
.. |Script| replace:: :class:`~fife_rpg.systems.scriptingsystem.Script`
.. |ScriptingSystem| replace:: :class:`~fife_rpg.systems.scriptingsystem.ScriptingSystem`